apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component7
    app.kubernetes.io/part-of: test-app
  name: test-component7
  namespace: jvm-bld-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component7
    spec:
      containers:
      - image: quay.io/psturc/test-images@sha256:0c32917f44de60419b574098fcb5df5777cd85797976efa27466f7197a5eb498
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
