apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: test-component5
  namespace: jvm-bld-test
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        appstudio.openshift.io/application: test-app
        appstudio.openshift.io/component: test-component5
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: test-component5-
      labels:
        appstudio.openshift.io/application: test-app
        appstudio.openshift.io/component: test-component5
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: jvm-bld-test
    spec:
      params:
      - name: git-url
        value: https://github.com/psturc-org/devfile-sample-hello-world
      - name: output-image
        value: quay.io/psturc/test-images:test-kcp-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio-tekton-catalog/pipeline-docker-build:9212817dcd58ed82930ffb0156706377d8422286
        name: docker-build
      podTemplate:
        imagePullSecrets:
        - name: redhat-appstudio-registry-pull-secret
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
